[package]
name = "soltop"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tokio = { version = "1.48.0", features = ["full"] }

[lib]
name = "soltop"
path = "src/lib.rs"

[[bin]]
name = "soltop"
path = "src/main.rs"
